// This file was auto-generated by ML.NET Model Builder. 

using System;
using BootstrapThingML.Model;

namespace BootstrapThingML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Id = 1F,
                Userid = 8F,
                PostedDate = @"'04/23/2001'",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Content with predicted Content from sample data...\n\n");
            Console.WriteLine($"Id: {sampleData.Id}");
            Console.WriteLine($"Userid: {sampleData.Userid}");
            Console.WriteLine($"PostedDate: {sampleData.PostedDate}");
            Console.WriteLine($"\n\nPredicted Content value {predictionResult.Prediction} \nPredicted Content scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
