// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BootstrapThingML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("Content"), LoadColumn(1)]
        public string Content { get; set; }


        [ColumnName("Userid"), LoadColumn(2)]
        public float Userid { get; set; }


        [ColumnName("PostedDate"), LoadColumn(3)]
        public string PostedDate { get; set; }


    }
}
